# Generated by Django 4.0.4 on 2022-05-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('contact', models.CharField(help_text='Ingrese un número de contacto', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(verbose_name='Hora del pedido')),
                ('contenido_pedido', models.CharField(help_text='Qué desea pedir?', max_length=200)),
                ('estatus', models.CharField(blank=True, choices=[('p', 'En preparación'), ('e', 'Entregado')], default='p', help_text='Estatus del pedido', max_length=1)),
                ('usuarios_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.usuario')),
            ],
        ),
    ]
